[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ground_relay = "6v2peeoZVj2AXfczVLqyMUTHYt3XQPqAxCktpTwjUZap"

[programs.devnet]
ground_relay = "6v2peeoZVj2AXfczVLqyMUTHYt3XQPqAxCktpTwjUZap"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/ground-relay/Cargo.toml"
