[package]
name = "ground-relay-program"
version = "0.1.0"
description = "Solana escrow and task state for Ground Relay"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ground_relay"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "1.2.0"
anchor-spl = "1.2.0"
